<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SaaSApp.HangfireWorker</RootNamespace>
    <AssemblyName>SaaSApp.HangfireWorker</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <!-- Postgres (new) -->
    <PackageReference Include="Hangfire.PostgreSql" Version="1.21.1" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.14" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\Logging\SaaSApp.Logging.csproj" />
    <ProjectReference Include="..\..\Modules\Users\Users.Infrastructure\SaaSApp.Users.Infrastructure.csproj" />
  </ItemGroup>
</Project>
