// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SaaSApp.Users.Infrastructure.Persistence;

#nullable disable

namespace SaaSApp.Users.Infrastructure.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    partial class UsersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("users")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SaaSApp.Users.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Groups", "users");
                });

            modelBuilder.Entity("SaaSApp.Users.Domain.Entities.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RoutePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Menus", "users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2000001-0000-4000-8000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 8, 10, 11, 1, 15, 839, DateTimeKind.Utc).AddTicks(6847),
                            IsDeleted = false,
                            IsSystem = true,
                            Key = "dashboard",
                            Label = "Dashboard",
                            RoutePath = "/dashboard",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("b2000001-0000-4000-8000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 8, 10, 11, 1, 15, 839, DateTimeKind.Utc).AddTicks(6898),
                            IsDeleted = false,
                            IsSystem = true,
                            Key = "inbox",
                            Label = "Inbox",
                            RoutePath = "/inbox",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("b2000001-0000-4000-8000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 8, 10, 11, 1, 15, 839, DateTimeKind.Utc).AddTicks(6906),
                            IsDeleted = false,
                            IsSystem = true,
                            Key = "ocr-review",
                            Label = "OCR.Review",
                            RoutePath = "/ocr-review",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("b2000001-0000-4000-8000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 8, 10, 11, 1, 15, 839, DateTimeKind.Utc).AddTicks(6913),
                            IsDeleted = false,
                            IsSystem = true,
                            Key = "processed-invoices",
                            Label = "Processed Invoices",
                            RoutePath = "/processed-invoices",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("b2000001-0000-4000-8000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 8, 10, 11, 1, 15, 839, DateTimeKind.Utc).AddTicks(6920),
                            IsDeleted = false,
                            IsSystem = true,
                            Key = "approval-queue",
                            Label = "Approval Queue",
                            RoutePath = "/approval-queue",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("b2000001-0000-4000-8000-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 8, 10, 11, 1, 15, 839, DateTimeKind.Utc).AddTicks(6931),
                            IsDeleted = false,
                            IsSystem = true,
                            Key = "vendors",
                            Label = "Vendors",
                            RoutePath = "/vendors",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("SaaSApp.Users.Domain.Entities.PermissionCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("PermissionCategories", "users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000006"),
                            IsActive = true,
                            Key = "dashboard",
                            Name = "Dashboard",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000001"),
                            IsActive = true,
                            Key = "workflow",
                            Name = "Workflow",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000002"),
                            IsActive = true,
                            Key = "folder",
                            Name = "Folder",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000003"),
                            IsActive = true,
                            Key = "task",
                            Name = "Task",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000004"),
                            IsActive = true,
                            Key = "workspace",
                            Name = "Workspace",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000005"),
                            IsActive = true,
                            Key = "settings",
                            Name = "Settings",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("SaaSApp.Users.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Roles", "users");
                });

            modelBuilder.Entity("SaaSApp.Users.Domain.Entities.RoleMenu", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefaultLanding")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("RoleMenus", "users");
                });

            modelBuilder.Entity("SaaSApp.Users.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("PermissionKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionKey");

                    b.ToTable("RolePermissions", "users");
                });

            modelBuilder.Entity("SaaSApp.Users.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AccountExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuthStrategy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AvatarPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("BusinessUnit")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Configuration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("CountryCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Department")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("ForcePasswordResetOnLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("GoogleSubjectId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GroupName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("IdCardPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("LastName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Location")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LoginName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LoginType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("MfaMethods")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MicrosoftOid")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int?>("PasswordAge")
                        .HasColumnType("integer");

                    b.Property<int>("PasswordExpiryDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(90);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PinHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProfileId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SecondaryEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SignaturePath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TotpSecretEncrypted")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("TwoFactorAuthentication")
                        .HasColumnType("boolean");

                    b.Property<string>("UiPreference")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("UserType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Users", "users");
                });

            modelBuilder.Entity("SaaSApp.Users.Domain.Entities.UserGroup", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("GroupId", "UserId");

                    b.ToTable("UserGroups", "users");
                });

            modelBuilder.Entity("SaaSApp.Users.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "UserId");

                    b.ToTable("UserRoles", "users");
                });

            modelBuilder.Entity("SaaSApp.Users.Domain.Entities.RoleMenu", b =>
                {
                    b.HasOne("SaaSApp.Users.Domain.Entities.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaaSApp.Users.Domain.Entities.Role", "Role")
                        .WithMany("Menus")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SaaSApp.Users.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("SaaSApp.Users.Domain.Entities.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SaaSApp.Users.Domain.Entities.UserGroup", b =>
                {
                    b.HasOne("SaaSApp.Users.Domain.Entities.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SaaSApp.Users.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("SaaSApp.Users.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SaaSApp.Users.Domain.Entities.Group", b =>
                {
                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("SaaSApp.Users.Domain.Entities.Role", b =>
                {
                    b.Navigation("Menus");

                    b.Navigation("Permissions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
